#!/bin/bash

#/ NAME
#/     puddle-init -- make a Python virtualenv
#/
#/ SYNOPSIS
#/     puddle init where]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local vhome="."

  local cmd_venv="$shome/bin/virtualenv"
  if [[ ! -x "$cmd_venv" ]]; then
    cmd_venv="$shome/libexec/virtualenv.py"
  fi

  $cmd_venv --extra-search-dir=$shome/vendor/cache --never-download "$vhome"

  "$shome/bin/puddle" install pip2pi virtualenv
}

require sub "$BASH_SOURCE" "$@"
