#!/bin/bash

#/ NAME
#/     puddle-shell -- bash subshell with puddle virtualenv activated
#/
#/ SYNOPSIS
#/     puddle shell

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  "$shome/bin/puddle" init .

  set +u; source "$shome/bin/activate"; set -u

  local ghome="$(cd -P "./$(git rev-parse --show-cdup)" && pwd -P)"
  set +u; source "$ghome/bin/activate"; set -u
  exec bash
}

require sub "$BASH_SOURCE" "$@"
