#!/bin/bash

#/ NAME
#/     puddle-init -- make a Python virtualenv
#/
#/ SYNOPSIS
#/     puddle init where]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local vhome="$1"; shift

  if [[ ! -x "$vhome/bin/python" ]]; then
    python $shome/libexec/virtualenv.py --extra-search-dir=$shome/vendor --never-download "$vhome"
  fi

  "$shome/bin/puddle" install pip2pi
}

require sub "$BASH_SOURCE" "$@"
