#!/bin/bash

#/ NAME
#/     puddle-cache -- dowload pip package and create index
#/
#/ SYNOPSIS
#/     puddle cache [cache] [packages...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local pth_cache="$1"; shift

   pip install --download-directory "$pth_cache" "$@"
   dir2pi "$pth_cache"
}

require sub "$BASH_SOURCE" "$@"
