#!/bin/bash

#/ NAME
#/     puddle-install -- install cached package
#/
#/ SYNOPSIS
#/     puddle install [packages...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local ghome="$(cd -P "./$(git rev-parse --show-cdup)" && pwd -P)"
  local pth_cache="$ghome/vendor/cache"

  set +u; source $ghome/bin/activate; set -u
  pip install --upgrade --index-url=file://"$pth_cache/simple" "$@"
}

require sub "$BASH_SOURCE" "$@"
