#!/bin/bash

#/ NAME
#/     puddle-install -- install cached package
#/
#/ SYNOPSIS
#/     puddle install [cache] [packages...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local pth_cache="$1"; shift

   pip install --index-url=file://"$pth_cache" "$@"
}

require sub "$BASH_SOURCE" "$@"
