#!/bin/bash

#/ NAME
#/     setup-virtualenv -- make a Python virtualenv
#/
#/ SYNOPSIS
#/     setup virtualenv [where]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local vhome="$1"; shift

  if [[ ! -x "$vhome/.awscli/bin/python" ]]; then
    python $shome/libexec/virtualenv.py --extra-search-dir=$shome/vendor --never-download "$vhome"
  fi
}

require sub "$BASH_SOURCE" "$@"
